resources:
  - '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
    name: jellyfin_token
    generic_secret:
      secret:
        filename: /etc/broker/jellyfin/token.txt
