resources:
  - '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
    name: caldav_basic
    generic_secret:
      secret:
        inline_string: "Basic REPLACE_WITH_BASE64_USER_PASS"
