/**
 * Sprint 39 S1: mTLS CA / server / client certs for remote broker topology.
 */
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const CERT_DAYS = '825';

export interface BrokerCertPaths {
  readonly caKey: string;
  readonly caCrt: string;
  readonly serverKey: string;
  readonly serverCrt: string;
  readonly clientKey: string;
  readonly clientCrt: string;
}

export function ensureOpenSsl(): void {
  try {
    execFileSync('openssl', ['version'], { stdio: 'pipe' });
  } catch {
    throw new Error('openssl not found — required for remote broker mode');
  }
}

function openssl(args: string[]): void {
  execFileSync('openssl', args, { stdio: 'pipe' });
}

function isIp(host: string): boolean {
  return /^\d{1,3}(\.\d{1,3}){3}$/.test(host) || host.includes(':');
}

function writeSanExt(path: string, host: string): void {
  const lines = ['subjectAltName = @alt_names', '[alt_names]'];
  if (isIp(host)) {
    lines.push(`IP.1 = ${host}`);
  } else {
    lines.push(`DNS.1 = ${host}`);
  }
  writeFileSync(path, `${lines.join('\n')}\n`, 'utf8');
}

/** Generate CA, server cert (broker host), client cert (core forwarder). */
export function generateBrokerCerts(root: string, brokerHost: string): BrokerCertPaths {
  ensureOpenSsl();

  const caDir = join(root, 'deploy', 'broker-remote', 'certs', 'ca');
  const serverDir = join(root, 'deploy', 'broker-remote', 'certs', 'server');
  const clientDir = join(root, 'deploy', 'broker-client', 'certs', 'client');
  mkdirSync(caDir, { recursive: true });
  mkdirSync(serverDir, { recursive: true });
  mkdirSync(clientDir, { recursive: true });

  const caKey = join(caDir, 'ca.key');
  const caCrt = join(caDir, 'ca.crt');
  openssl(['genrsa', '-out', caKey, '4096']);
  openssl([
    'req',
    '-x509',
    '-new',
    '-nodes',
    '-key',
    caKey,
    '-days',
    CERT_DAYS,
    '-out',
    caCrt,
    '-subj',
    '/CN=AEGIS Broker CA',
  ]);

  const serverKey = join(serverDir, 'server.key');
  const serverCsr = join(serverDir, 'server.csr');
  const serverCrt = join(serverDir, 'server.crt');
  const serverExt = join(serverDir, 'server.ext');
  writeSanExt(serverExt, brokerHost);
  openssl(['genrsa', '-out', serverKey, '2048']);
  openssl(['req', '-new', '-key', serverKey, '-out', serverCsr, '-subj', `/CN=${brokerHost}`]);
  openssl([
    'x509',
    '-req',
    '-in',
    serverCsr,
    '-CA',
    caCrt,
    '-CAkey',
    caKey,
    '-CAcreateserial',
    '-out',
    serverCrt,
    '-days',
    CERT_DAYS,
    '-extfile',
    serverExt,
  ]);

  const clientKey = join(clientDir, 'client.key');
  const clientCsr = join(clientDir, 'client.csr');
  const clientCrt = join(clientDir, 'client.crt');
  openssl(['genrsa', '-out', clientKey, '2048']);
  openssl(['req', '-new', '-key', clientKey, '-out', clientCsr, '-subj', '/CN=aegis-core']);
  openssl([
    'x509',
    '-req',
    '-in',
    clientCsr,
    '-CA',
    caCrt,
    '-CAkey',
    caKey,
    '-CAcreateserial',
    '-out',
    clientCrt,
    '-days',
    CERT_DAYS,
  ]);

  copyFileSync(caCrt, join(serverDir, 'ca.crt'));
  copyFileSync(caCrt, join(clientDir, 'ca.crt'));

  return { caKey, caCrt, serverKey, serverCrt, clientKey, clientCrt };
}

export function renderBrokerClientEnvoy(remoteHost: string, port = 8443): string {
  const host = remoteHost.trim();
  if (host.length === 0) throw new Error('broker remote host is required');
  return `# Generated by aegis-setup — mTLS forwarder to remote broker
node:
  id: aegis-broker-client
  cluster: aegis

static_resources:
  listeners:
    - name: client_forwarder
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: broker_client
                route_config:
                  name: forward
                  virtual_hosts:
                    - name: forward_all
                      domains: ['*']
                      routes:
                        - match: { prefix: '/' }
                          route:
                            cluster: remote_broker
                            timeout: 30s
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: remote_broker
      type: STRICT_DNS
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: ${host}
          common_tls_context:
            tls_certificates:
              - certificate_chain: { filename: /etc/broker-client/tls/client.crt }
                private_key: { filename: /etc/broker-client/tls/client.key }
            validation_context:
              trusted_ca:
                filename: /etc/broker-client/tls/ca.crt
      load_assignment:
        cluster_name: remote_broker
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: ${host}, port_value: ${port} }
`;
}
