/**
 * Генераторы файлов установки F9 (шаблоны из deploy/ репозитория).
 */
import { randomBytes } from 'node:crypto';

export type BrokerMode = 'local' | 'remote';

export interface SetupInput {
  readonly dataDir: string;
  readonly llmBaseUrl: string;
  readonly llmModel: string;
  readonly qLlmBaseUrl: string;
  readonly qLlmModel: string;
  readonly pairingCode: string;
  readonly brokerMode?: BrokerMode;
  readonly brokerRemoteHost?: string;
}

export function generatePairingCode(): string {
  return `aegis-${randomBytes(4).toString('hex')}`;
}

export function generateConfig(input: SetupInput): string {
  const brokerHost =
    input.brokerMode === 'remote' ? 'aegis-broker-client:8080' : 'aegis-broker:8080';
  const cfg = {
    data_dir: input.dataDir,
    skills_dir: './skills',
    budget: {
      daily_token_limit: 100_000,
      reserve_for_owner: 20_000,
      notify_session_id: 'tg:REPLACE_AFTER_PAIRING',
    },
    schedules: [],
    learning: {
      self_improvement_llm_enabled: false,
      min_reuse_rate: 0,
      memory_consolidation_enabled: false,
      consolidation_batch_size: 25,
      research_deep_enabled: false,
      research_deep_branch_count: 3,
      research_deep_token_cap: 12000,
    },
    memory: {
      context: {
        enabled: true,
        dialog_tail: 10,
        recall_k: 3,
        max_tokens: 2048,
      },
    },
    web: {
      max_response_kb: 512,
      cache_ttl_s: 3600,
      broker_host: brokerHost,
    },
    sandbox: {
      workspace_dir: './workspace',
    },
    mcp: { servers: [] },
    llm: {
      p_llm: {
        base_url: input.llmBaseUrl,
        model: input.llmModel,
        key_ref: 'AEGIS_P_LLM_KEY',
        max_tokens: 4096,
      },
      q_llm: {
        base_url: input.qLlmBaseUrl,
        model: input.qLlmModel,
        key_ref: 'AEGIS_Q_LLM_KEY',
        max_tokens: 2048,
      },
    },
    telegram: {
      bot_token_ref: 'AEGIS_TG_BOT_TOKEN',
      pairing_code_ref: 'AEGIS_TG_PAIRING_CODE',
      poll_timeout_s: 30,
    },
    webchat: {
      enabled: true,
      host: '127.0.0.1',
      port: 8790,
      pairing_code_ref: 'AEGIS_WEBCHAT_PAIRING_CODE',
    },
  };
  return `${JSON.stringify(cfg, null, 2)}\n`;
}

export function generateHostEnv(pairingCode: string): string {
  return `# AEGIS host environment — source before npm start
# Generated by aegis-setup. Do not commit secrets.

AEGIS_CONFIG=./aegis.config.json
AEGIS_P_LLM_KEY=
AEGIS_Q_LLM_KEY=
AEGIS_TG_BOT_TOKEN=
AEGIS_TG_PAIRING_CODE=${pairingCode}
AEGIS_WEBCHAT_PAIRING_CODE=${pairingCode}
AEGIS_MATRIX_HOMESERVER=
AEGIS_MATRIX_ACCESS_TOKEN=
AEGIS_MATRIX_PAIRING_CODE=${pairingCode}
AEGIS_SLACK_BOT_TOKEN=
AEGIS_SLACK_APP_TOKEN=
AEGIS_SLACK_PAIRING_CODE=${pairingCode}
AEGIS_SANDBOX_IMAGE=alpine:3.20
AEGIS_INTERNAL_NETWORK=aegis-internal
AEGIS_MCP_SANDBOX_IMAGE=node:24-alpine
`;
}

export function generateComposeEnv(
  brokerSecretPath: string,
  opts?: { brokerMode?: BrokerMode; brokerRemoteHost?: string },
): string {
  const lines = [
    '# Docker Compose env — used by deploy/docker-compose.yml',
    '# Generated by aegis-setup',
    '',
    'AEGIS_TG_BOT_TOKEN=',
    'AEGIS_TG_PAIRING_CODE=',
  ];
  if (opts?.brokerMode === 'remote') {
    lines.push('COMPOSE_PROFILES=remote-broker');
    lines.push(`BROKER_REMOTE_HOST=${opts.brokerRemoteHost ?? ''}`);
    lines.push('BROKER_REMOTE_PORT=8443');
  } else {
    lines.push(`AEGIS_BROKER_SECRET_FILE=${brokerSecretPath}`);
  }
  return `${lines.join('\n')}\n`;
}

const ENVOY_PIN =
  'envoyproxy/envoy:v1.37.1@sha256:29496a88fba9c4c9cdef4afe8fec70f536c5ba111b1c2bddbc5436b091ceca33';

/** Pinned topology from deploy/docker-compose.yml (Sprint 3/10). */
export function generateDockerCompose(mode: BrokerMode = 'local'): string {
  if (mode === 'remote') {
    return `# Generated by aegis-setup — remote broker mode (Sprint 39 S1)
services:
  broker-client:
    profiles: [remote-broker]
    container_name: aegis-broker-client
    image: ${ENVOY_PIN}
    restart: unless-stopped
    command: ['envoy', '-c', '/etc/broker-client/envoy.yaml']
    networks: [aegis-internal, aegis-egress]
    volumes:
      - ./broker-client/envoy.yaml:/etc/broker-client/envoy.yaml:ro
      - ./broker-client/certs/client:/etc/broker-client/tls:ro

networks:
  aegis-internal:
    internal: true
  aegis-egress: {}
`;
  }
  return `# Generated by aegis-setup — see deploy/broker/README.md
services:
  broker:
    image: ${ENVOY_PIN}
    restart: unless-stopped
    command: ['envoy', '-c', '/etc/broker/envoy.yaml']
    networks: [aegis-internal, aegis-egress]
    volumes:
      - ./broker/envoy.yaml:/etc/broker/envoy.yaml:ro
      - ./broker/secret.yaml:/etc/broker/secret.yaml:ro
      - \${AEGIS_BROKER_SECRET_FILE}:/etc/broker/token.txt:ro

networks:
  aegis-internal:
    internal: true
  aegis-egress: {}
`;
}

export const SETUP_VERSION = 1;

export function setupManifest(opts?: {
  brokerMode?: BrokerMode;
  brokerRemoteHost?: string;
}): string {
  const body: Record<string, unknown> = { setup_version: SETUP_VERSION, generator: 'aegis-setup' };
  if (opts?.brokerMode !== undefined) body.broker_mode = opts.brokerMode;
  if (opts?.brokerRemoteHost !== undefined) body.broker_remote_host = opts.brokerRemoteHost;
  return `${JSON.stringify(body, null, 2)}\n`;
}
