resources:
  - '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
    name: travel_aviation_key
    generic_secret:
      secret:
        filename: /etc/broker/travel/api-key.txt
